### PR TITLE
Update repos.json

### PR DESCRIPTION
**Pull request by ludeeus**
This JSON file was made with https://github.com/ludeeus/customjson 
Please look over the info that changes in this PR.

CC @thomasloven

### CODE REVIEW

**Comment by ludeeus** [comment]
I really want to move over to this approach since it's more stable and will enable devs to check their info and potentially force an update.

**Comment by ludeeus** [comment]
Unless anyone objects, I'm going to implement it in a few days.

**Review by iantrich — APPROVED** [review]

**Comment by ludeeus** [comment]
I have not enabled a Travis cron job for this that will run (and generate a new file) every 24h.
First run is  `2019-01-07T12:21:00Z`

**Comment by ludeeus** [comment]
ups.. This is already live :)
If you see an issue with the data please open a issue here https://github.com/ludeeus/customjson/issues
or hit me up on Discord

**Pull request closed without merging**
